### ISSUE TITLE
Problems by Installing Hydpy

### ISSUE THREAD

**Issue by JKupzig** [hydpy-dev/hydpy#35]
System: Windows 10
Python Version: 3.7 (Aanaconda3 - environment "p37")
Hydpy Version: 3.1.1 (GitHub)

Steps I did: 
1) Downloading all required packages with conda in environment (bokeh, numpy, ...)
2) Downloading Hydpy-3.1.1 folder from Git Hub and unzip
3) Downloading Python Launcher for Windows
4) Downloading C-Compiler for Windows (microsoft visual studio 2019) 
5) running python setup.py install in anaconda prompt from environment

Problems: 
1) It seems like the testeverything.py et the end of the installing from setup.py detects some issues that I can't solve 
--> "There is no hydpy.core"  .... --> Use hydpy with caution
2) When importing hydpy in python an ImportError raises: 
import hydpy
Traceback (most recent call last):

  File "<ipython-input-1-f1529f5834ed>", line 1, in <module>
    import hydpy

  File "C:\Users\Jenny\Documents\0_Master\Masterarbeit\Aktuell\hydpy-3.1\hydpy\__init__.py", line 13, in <module>
    from hydpy.core.exceptiontools import OptionalImport

  File "C:\Users\Jenny\Documents\0_Master\Masterarbeit\Aktuell\hydpy-3.1\hydpy\core\exceptiontools.py", line 7, in <module>
    from hydpy.core import autodoctools

  File "C:\Users\Jenny\Documents\0_Master\Masterarbeit\Aktuell\hydpy-3.1\hydpy\core\autodoctools.py", line 36, in <module>
    from hydpy.cythons import annutils

ImportError: cannot import name 'annutils' from 'hydpy.cythons' (C:\Users\Jenny\Documents\0_Master\Masterarbeit\Aktuell\hydpy-3.1\hydpy\cythons\__init__.py)

Any idea what I did wrong? Is there a guide for installation besides the one from https://hydpy-dev.github.io/hydpy/install.html ?

**Comment by JKupzig** [comment]
Additional Information: 
Installed nlopt with conda install -c conda-forge nlopt in anaconda prompt as well because of planned calibration with this package

**Comment by tyralla** [comment]
Hi Jenny!

You can install version 3.1.1 from the [Python Package Index](https://pypi.org/project/HydPy/ ) directly via `pip install hydpy`.  Then there is no need to build any binaries on your own. To build from source (because you are working on 32 bit or because you are going to implement a new model) requires more effort. 

In your case, I suspect an "environmental problem". 

First, I am afraid the `python test_everything` command within `setup.py` does not respect your environment selection.  However, you can activate the environment and trigger the test routines by writing `python test_everything` yourself, to see if everything works fine.

Second, you tried to import from the downloaded *hydpy* folder directly.  This folder comes without the required Cython extension files (e.g. annutils.pyd), which are generated during the build process.  Open the command line prompt in another directory, activate your environment, start python, and write `import hydpy` to see if the *HydPy* installation in your environment works.  

Note that, after a successful build (when `test_everyting.py` does not detect any problems), all relevant generated files (especially the extension files) are copied back to the local *hydpy* folder.

**Comment by tyralla** [comment]
Some recent changes for building a *HydPy* installer for Windows might have solved your problem.  If you are still interested, you can download the related code from the [windows installer branch](https://github.com/hydpy-dev/hydpy/tree/feature/windows_installer) and see if it works. 

(I will merge this branch into the [master branch](https://github.com/hydpy-dev/hydpy) soon.  So, please download the from the master branch if the windows installer branch does not exist anymore.)

**Comment by tyralla** [comment]
Checked it myself for a conda environment in the meantime, and works fine.  Please reopen if you encounter problems with other types of environments.
