### ISSUE TITLE
Enable reading constant series

### ISSUE THREAD

**Issue by sivogel** [hydpy-dev/hydpy#76]
The dam models currently get evaporation and precipitation series as input. Sometimes it is wanted to set them to 0 and rather consider precipitation and evaporation on the dam surface as water bodies within a land model. Currently it is not possible to read a constant value for a series. Currently, zero-values for the whole desired timegrid have to be defined in the input series.

**Comment by tyralla** [comment]
I turned the input sequences `Precipitation` and `Evaporation` into the flux sequences `Precipitation` and `PotentialEvaporation`.  All dam models can determine their values using submodels that comply with the `PrecipModel_V2` or `PETModel_V1` interface.  Using these submodels is optional.  As long as no submodel is available, the value of the respective series is generally set to zero. 

The title of this issue is more general, as it also implies default values different from zero.  However, I see no relevant use case for constant precipitation or evaporation that is non-zero.  If such a demand arises, we can implement submodels that support defining constant values via control parameters.

Also, the title is not restricted to HydPy-Dam.  The other input sequences for which we frequently define constant (zero) time series are [FXS](https://hydpy-dev.github.io/hydpy/5.0/wland.html#hydpy.models.wland.wland_fluxes.FXS) and [FXG](https://hydpy-dev.github.io/hydpy/5.0/wland.html#hydpy.models.wland.wland_fluxes.FXG).  Still, we rejected implementing the corresponding submodels and adding them to HydPy-W because these sequences are closely connected to the WALRUS model concept.

Implemented in 1b893fdc43f84306139f24652325a244274e5750 and soon in the master branch.
